# Generated by Django 2.2.19 on 2021-03-31 00:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("mainapp", "0006_products_is_active"),
    ]

    operations = [
        migrations.AlterField(
            model_name="productcategory",
            name="is_active",
            field=models.BooleanField(db_index=True, default=True, verbose_name="категория активна"),
        ),
        migrations.AlterField(
            model_name="products",
            name="is_active",
            field=models.BooleanField(db_index=True, default=True, verbose_name="продукт активен"),
        ),
    ]
