# Generated by Django 2.2.19 on 2021-03-31 00:43

import datetime

from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ("authnapp", "0006_auto_20210317_1601"),
    ]

    operations = [
        migrations.AlterField(
            model_name="shopuser",
            name="activation_key_expires",
            field=models.DateTimeField(
                default=datetime.datetime(2021, 4, 2, 0, 43, 14, 88512, tzinfo=utc), verbose_name="актуальность ключа"
            ),
        ),
    ]
