# Generated by Django 2.2.19 on 2021-04-05 00:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("authnapp", "0007_auto_20210324_1827"),
        ("authnapp", "0007_auto_20210331_0043"),
    ]

    operations = []
